### ISSUE TITLE
Compiler Task Force - Master Issue

### ISSUE THREAD

**Issue by elegios** [miking-lang/miking#187]
This issue serves as the master issue for the current task of getting a compiler working for mexpr. 

- [x] Compilation from MExpr to intermediate OCamlish, then pretty printing. The first step only covers constants and simple expressions, and does not keep metadata, but does pretty print somewhat reasonably (indenting only, we do not consider precedence). @lingmar @br4sco @larshum 
  - [x] Rebase on recent changes
  - [x] Reuse Const pretty-printing
  - [x] Escaping of identifiers
  - [x] and printing them uniquely
  - [x] Parentheses around atomic expressions and left associative function application (but do not handle any other precedence or associativity, only do prefix functions)
- [x] Testing the compilation (comparing result of running interpreter vs compiling and asking ocaml to run it)
- [x] Extend the previous step to support lambdas and let.
- [x] Make a function that does the compilation with a nice interface, that also allows using the intrinsics library
- [ ] Research into data type representation. @elegios @david-broman 
  - [ ] Research into record representation. Includes sharing field names between different record types, record extensions, and row polymorphism.
  - [ ] List of fairly exhaustive ways to use values and how those example programs would be compiled
- [ ] Lifting of constructors
- [ ] Grouping constructors by return type and generate OCaml types
- [ ] Incorporate metadata from the parser.
- [ ] Wrap literals in `Obj.repr` and arguments to intrinsics in `Obj.obj`. This task probably includes generating let's before the program binding intrinsics to appropriately Objified types. Possibly also a `r` function instead of `Obj.repr`, just for brevity.
- [x] How do we compile sequences?
  - [x] Actually do it
- [x] How do we compile symbols (`gensym`)?
- [x] Pattern compilation @elegios 
- [ ] How do we compile `utest`?
  - [ ] Actually do it
- [x] Add intrinsics so that we can bootstrap the compilation process
  - [/] Add support for these and others in `pprint.mc` for OCaml
- [x] Implement floating point stuff (this is blocked on the parser not being able to parse them)
  - [x] Add float support to the parser

**Comment by br4sco** [comment]
So I have been thinking a little about the OCaml interface towards sequence and symbol intrinsics. The idea so far:

Create a module, named say `Intrinsics`, containing the ocaml versions of `cons`, `snoc`, `makeSeq`, etc., as well as `gensym`, `eqsym` (we could very well interface all intrinsics here instead of calling the corresponding operators in the generated ocaml code (or `boot` for that matter) directly e.g. `(+)`, `(-)`, ..., but maybe that is a bit excessive). I think this gives a nice clean interface to be made available in the generated ocaml code as well as in `boot`. However, we cannot directly use this module in `boot` since we internally rely on `map`, `fold_right`, `etc` over sequences (finger trees), so we would have to add these by extending `Intrinsics` in `boot` (using include in the module I guess).

**Comment by david-broman** [comment]
Good point. However, we have to double check so that we do not get an overhead in the compiled code due to an indirection via a module. Especially if `(+)`, `(-)` etc. are included. I guess the only way to really check this is to inspect the generated assembly code.

**Comment by br4sco** [comment]
Intrinsics we can compile to ocaml and are tested.
- [x] `addi`
- [x] `subi`
- [x] `muli`
- [x] `divi`
- [x] `modi`
- [x] `negi`
- [x] `lti`
- [x] `leqi`
- [x] `gti`
- [x] `geqi`
- [x] `eqi`
- [x] `neqi`
- [x] `slli`
- [x] `srli`
- [x] `srai`
- [ ] `arity`
- [x] `addf`
- [x] `subf`
- [x] `mulf`
- [x] `divf`
- [x] `negf`
- [x] `ltf`
- [x] `leqf`
- [x] `gtf`
- [x] `geqf`
- [x] `eqf`
- [x] `neqf`
- [x] `floorfi`
- [x] `ceilfi`
- [x] `roundfi`
- [x] `int2float`
- [x] `string2float`
- [x] `eqc`
- [x] `char2int`
- [x] `int2char`
- [ ] `create`
- [x] `length`
- [x] `concat`
- [x] `get`
- [x] `set`
- [x] `cons`
- [x] `snoc`
- [ ] `splitAt`
- [x] `reverse`
- [ ] `subsequence`
- [ ] `print`
- [ ] `dprint`
- [ ] `readLine`
- [ ] `readBytesAsString`
- [ ] `argv`
- [ ] `readFile`
- [ ] `writeFile`
- [ ] `fileExists`
- [ ] `deleteFile`
- [ ] `error`
- [ ] `exit`
- [ ] `eqsym`
- [ ] `gensym`
- [ ] `sym2hash`
- [x] `randIntU`
- [x] `randSetSeed`
- [ ] `wallTimeMs`
- [ ] `sleepMs`
- [ ] `mapEmpty`
- [ ] `mapInsert`
- [ ] `mapRemove`
- [ ] `mapFind`
- [ ] `mapAny`
- [ ] `mapMem`
- [ ] `mapMap`
- [ ] `mapMapWithKey`
- [ ] `mapBindings`
- [ ] `tensorCreate`
- [ ] `tensorGetExn`
- [ ] `tensorSetExn`
- [ ] `tensorRank`
- [ ] `tensorShape`
- [ ] `tensorReshapeExn`
- [ ] `tensorCopyExn`
- [ ] `tensorSliceExn`
- [ ] `tensorSubExn`
- [ ] `tensorIteri`
- [ ] `bootParserParseMExprString`
- [ ] `bootParserGetId`
- [ ] `bootParserGetTerm`
- [ ] `bootParserGetString`
- [ ] `bootParserGetInt`
- [ ] `bootParserGetFloat`
- [ ] `bootParserGetListLength`
- [ ] `bootParserGetConst`
- [ ] `bootParserGetPat`
- [ ] `bootParserGetInfo`

**Comment by br4sco** [comment]
`CNot` is compiled but it doesn't exist in `boot` so it should probably be removed.
